/* global React */

// ---------- Course data ----------
const CATEGORIES = [
  { key: "cloud", label: "Cloud & IT", count: 24, blurb: "AWS, Azure, GCP, Kubernetes, SRE" },
  { key: "dev", label: "Software Development", count: 31, blurb: "Full-stack, systems, architecture" },
  { key: "pm", label: "Project Management", count: 18, blurb: "PMP, Agile, PRINCE2, Scrum" },
  { key: "quality", label: "Quality Management", count: 12, blurb: "Six Sigma, ISO, Lean" },
  { key: "data", label: "Data & AI", count: 22, blurb: "ML, LLM ops, analytics" },
  { key: "leadership", label: "Leadership", count: 9, blurb: "Executive, product, people" },
];

const COURSES = [
  {
    slug: "aws-solutions-architect",
    code: "CLD · 101",
    title: "AWS Certified Solutions Architect — Associate",
    cat: "cloud",
    catLabel: "Cloud & IT",
    short: "Design resilient, cost-efficient architectures on AWS and pass the SAA-C03 on first attempt.",
    level: "Intermediate",
    duration: "10 weeks",
    mode: "Live + Self-paced",
    cert: "AWS SAA-C03",
    price: 1495,
    compare: 1995,
    cohorts: 312,
    rating: 4.9,
    color: "#4A3AFF",
    featured: true,
    highlights: [
      "60+ hours of live, instructor-led sessions",
      "Architecture labs on real AWS accounts",
      "2 full-length mock exams with detailed review",
      "Exam voucher included, pass guarantee or retake free",
    ],
    outcomes: [
      "Design multi-tier, highly-available systems on AWS",
      "Select appropriate compute, storage, and networking services for any workload",
      "Apply cost, performance and security trade-offs confidently",
      "Pass the AWS SAA-C03 examination",
    ],
    audience: [
      "Engineers moving from on-prem to cloud",
      "Backend developers pursuing architecture roles",
      "Solutions engineers and technical pre-sales",
      "IT consultants preparing for cloud engagements",
    ],
    syllabus: [
      { title: "Foundations", hours: 6, items: ["Shared responsibility & IAM", "Regions, AZs, Edge", "The Well-Architected Framework"] },
      { title: "Compute & Containers", hours: 9, items: ["EC2, ASG, Spot", "ECS & EKS primer", "Serverless with Lambda"] },
      { title: "Storage & Databases", hours: 8, items: ["S3 classes & lifecycle", "EBS, EFS, FSx", "RDS, Aurora, DynamoDB"] },
      { title: "Networking", hours: 7, items: ["VPC design patterns", "Route 53, CloudFront", "Hybrid connectivity"] },
      { title: "Security & Compliance", hours: 6, items: ["KMS, Secrets Manager", "WAF & Shield", "Audit trails & GuardDuty"] },
      { title: "Resilience & Cost", hours: 7, items: ["DR strategies", "Cost optimization", "Monitoring & observability"] },
      { title: "Exam Readiness", hours: 8, items: ["Mock #1 + review", "Question decomposition", "Mock #2 + final review"] },
    ],
    faq: [
      { q: "Do I need prior AWS experience?", a: "No — we start from foundational concepts. Basic IT literacy (networking, Linux) is helpful but not required." },
      { q: "Is the exam voucher really included?", a: "Yes. A single-use voucher is issued after you complete the final mock with 75%+." },
      { q: "What if I don't pass?", a: "Retake the cohort at no cost within 12 months, or attend self-paced indefinitely." },
      { q: "Is this course GST-compliant for reimbursement?", a: "Yes — itemized invoices are issued for corporate reimbursement." },
    ],
  },
  {
    slug: "kubernetes-cka",
    code: "CLD · 204",
    title: "Certified Kubernetes Administrator (CKA)",
    cat: "cloud", catLabel: "Cloud & IT",
    short: "Operate production Kubernetes clusters with confidence. Hands-on, exam-aligned.",
    level: "Advanced", duration: "8 weeks", mode: "Live cohort", cert: "CNCF CKA",
    price: 1195, compare: 1595, cohorts: 184, rating: 4.9, color: "#2AB6B6",
    highlights: ["Kill-shell exam drills", "Real multi-node clusters", "kubectl muscle memory"],
    outcomes: ["Provision & secure clusters", "Troubleshoot under time pressure", "Pass CKA"],
    audience: ["DevOps / SRE", "Platform engineers", "Senior backend"],
    syllabus: [
      { title: "Cluster Architecture", hours: 5, items: ["Control plane", "etcd", "kubeadm"]},
      { title: "Workloads", hours: 6, items: ["Deployments, DaemonSets", "Jobs & CronJobs"]},
      { title: "Networking", hours: 6, items: ["CNI, Services", "Ingress & NetPol"]},
      { title: "Storage", hours: 4, items: ["PV, PVC, StorageClass"]},
      { title: "Security", hours: 5, items: ["RBAC, PSP/PSA"]},
      { title: "Exam Sprint", hours: 8, items: ["Timed labs", "Mock exam"]},
    ],
    faq: [],
  },
  {
    slug: "azure-administrator",
    code: "CLD · 108",
    title: "Microsoft Azure Administrator (AZ-104)",
    cat: "cloud", catLabel: "Cloud & IT",
    short: "Manage Azure identities, governance, storage, compute and networking end-to-end.",
    level: "Intermediate", duration: "9 weeks", mode: "Live cohort", cert: "Microsoft AZ-104",
    price: 1395, compare: 1795, cohorts: 211, rating: 4.8, color: "#0E77D6",
  },
  {
    slug: "pmp",
    code: "PMT · 101",
    title: "PMP® Exam Preparation",
    cat: "pm", catLabel: "Project Management",
    short: "35 contact hours, 2,000+ practice questions, and a proven pass methodology.",
    level: "Advanced", duration: "6 weeks", mode: "Weekend cohort", cert: "PMI PMP",
    price: 995, compare: 1395, cohorts: 428, rating: 4.9, color: "#0A0A0A",
    featured: true,
    highlights: [
      "35-hour PMI-approved contact training",
      "Predictive, Agile & Hybrid tracks aligned to the current ECO",
      "2,000+ practice questions in our adaptive engine",
      "1:1 application review before submission",
    ],
    outcomes: [
      "Pass the PMP on first attempt",
      "Lead predictive, agile and hybrid projects",
      "Apply PMI's People / Process / Business Environment lens",
    ],
    audience: ["Project & program managers", "Engineering leads", "Consultants"],
    syllabus: [
      { title: "People", hours: 12, items: ["Team leadership", "Conflict & negotiation", "Stakeholder engagement"] },
      { title: "Process", hours: 14, items: ["Planning & scheduling", "Risk & quality", "Procurement & vendors"] },
      { title: "Business Environment", hours: 6, items: ["Compliance", "Value delivery", "Organizational change"] },
      { title: "Agile & Hybrid", hours: 8, items: ["Scrum, Kanban", "Scaling frameworks", "Hybrid patterns"] },
      { title: "Exam Strategy", hours: 8, items: ["Question decomposition", "Mock #1 & #2", "Final review"] },
    ],
    faq: [
      { q: "Do I meet the eligibility requirements?", a: "We review your application in a 1:1 session — typically 36 months of project experience with a degree, or 60 without." },
      { q: "How long is PMP valid?", a: "Three years — renewable via 60 PDUs." },
    ],
  },
  {
    slug: "scrum-master",
    code: "PMT · 202",
    title: "Professional Scrum Master (PSM I + II)",
    cat: "pm", catLabel: "Project Management",
    short: "From scrum fundamentals to coaching at scale. Two certifications, one track.",
    level: "Intermediate", duration: "4 weeks", mode: "Live cohort", cert: "Scrum.org PSM",
    price: 695, compare: 895, cohorts: 267, rating: 4.8, color: "#6E4AFF",
  },
  {
    slug: "six-sigma-black-belt",
    code: "QLT · 301",
    title: "Lean Six Sigma Black Belt",
    cat: "quality", catLabel: "Quality Management",
    short: "Master DMAIC, advanced statistics and change leadership. Project review included.",
    level: "Advanced", duration: "14 weeks", mode: "Blended", cert: "IASSC Black Belt",
    price: 1895, compare: 2495, cohorts: 96, rating: 4.9, color: "#111111",
  },
  {
    slug: "iso-9001-lead-auditor",
    code: "QLT · 110",
    title: "ISO 9001:2015 Lead Auditor",
    cat: "quality", catLabel: "Quality Management",
    short: "IRCA-certified lead auditor program. Audit real QMS documentation end-to-end.",
    level: "Intermediate", duration: "5 weeks", mode: "Live cohort", cert: "IRCA Lead Auditor",
    price: 1095, compare: 1395, cohorts: 142, rating: 4.8, color: "#2E7D32",
  },
  {
    slug: "fullstack-ts",
    code: "DEV · 101",
    title: "Full-Stack TypeScript — Next.js, Postgres, tRPC",
    cat: "dev", catLabel: "Software Development",
    short: "Ship production-grade apps. Design, build, deploy — 4 capstone projects.",
    level: "Intermediate", duration: "12 weeks", mode: "Live + Self-paced", cert: "Studio Certificate",
    price: 1295, compare: 1695, cohorts: 189, rating: 4.9, color: "#0A0A0A",
    featured: true,
  },
  {
    slug: "system-design",
    code: "DEV · 305",
    title: "System Design for Senior Engineers",
    cat: "dev", catLabel: "Software Development",
    short: "Think in systems. Whiteboard with rigor. Interview with confidence.",
    level: "Advanced", duration: "8 weeks", mode: "Live cohort", cert: "Studio Certificate",
    price: 995, compare: 1295, cohorts: 231, rating: 4.9, color: "#C24A2E",
  },
  {
    slug: "ml-engineering",
    code: "DAT · 210",
    title: "Machine Learning Engineering",
    cat: "data", catLabel: "Data & AI",
    short: "From notebook to production: MLOps, feature stores, evaluation, monitoring.",
    level: "Advanced", duration: "10 weeks", mode: "Live cohort", cert: "Studio Certificate",
    price: 1595, compare: 1995, cohorts: 128, rating: 4.8, color: "#1E88E5",
  },
  {
    slug: "llm-engineering",
    code: "DAT · 301",
    title: "LLM Engineering in Production",
    cat: "data", catLabel: "Data & AI",
    short: "Build, evaluate and operate LLM-powered products without the hype cycle.",
    level: "Advanced", duration: "6 weeks", mode: "Live cohort", cert: "Studio Certificate",
    price: 1195, compare: 1495, cohorts: 87, rating: 4.9, color: "#7B3AED",
    featured: true,
  },
  {
    slug: "executive-leadership",
    code: "LDR · 101",
    title: "Executive Leadership Intensive",
    cat: "leadership", catLabel: "Leadership",
    short: "A 6-week program for senior leaders taking on expanded scope.",
    level: "Executive", duration: "6 weeks", mode: "Live cohort", cert: "Studio Certificate",
    price: 2495, compare: 2995, cohorts: 62, rating: 5.0, color: "#0A0A0A",
  },
];

// ---------- Testimonials / outcomes ----------
const OUTCOMES = [
  {
    quote: "The architecture labs felt indistinguishable from my day job — except I had room to fail. I walked out of the AWS exam with 842.",
    name: "Priya Raman",
    role: "Staff Engineer",
    org: "Fintech scale-up",
    metric: "Passed SAA-C03 · 842/1000",
    course: "aws-solutions-architect",
  },
  {
    quote: "We sent 140 engineers through the Kubernetes track in four months. Incident MTTR fell by 38%, and our on-call rotations stopped bleeding people.",
    name: "Martin Okafor",
    role: "VP Engineering",
    org: "Logistics platform",
    metric: "140 engineers · 38% ↓ MTTR",
    course: "kubernetes-cka",
  },
  {
    quote: "I'd failed the PMP twice before. The Studio's 1:1 application review and the way they teach question decomposition — that's what changed it.",
    name: "Anika Shetty",
    role: "Senior Program Manager",
    org: "Consulting firm",
    metric: "PMP Above Target · 3rd attempt",
    course: "pmp",
  },
  {
    quote: "The Black Belt capstone became an actual company project. We saved $2.1M in annualised waste on our packaging line.",
    name: "Diego Almeida",
    role: "Director of Operations",
    org: "CPG manufacturer",
    metric: "$2.1M annualised savings",
    course: "six-sigma-black-belt",
  },
];

// ---------- Corporate logos (original wordmarks) ----------
const CLIENTS = [
  "NORTHWIND",
  "Atelier & Co.",
  "MERIDIAN",
  "Halcyon Labs",
  "VOYAGER",
  "Forgehouse",
  "QUANTA",
  "Cassini Group",
  "HELIX",
  "OKAPI",
];

// ---------- Instructors ----------
const INSTRUCTORS = [
  { name: "Dr. Elena Vasquez", title: "Former Principal Architect, AWS", focus: "Cloud Architecture" },
  { name: "Rohan Mehta", title: "PMP, PgMP · 18 yrs at Big 4", focus: "Project Management" },
  { name: "Ada Nakamura", title: "Ex-Google SRE · Kubernetes maintainer", focus: "Platform Engineering" },
  { name: "Samuel Okonkwo", title: "Master Black Belt · ex-Toyota", focus: "Quality & Operations" },
  { name: "Lin Wei", title: "Ex-Stripe ML Infra Lead", focus: "Machine Learning" },
  { name: "Isabelle Laurent", title: "Executive Coach · Harvard MBA", focus: "Leadership" },
];

// ---------- Nav ----------
const NAV = [
  { to: "/", label: "Home" },
  { to: "/courses", label: "Courses" },
  { to: "/corporate", label: "Corporate" },
  { to: "/about", label: "About" },
  { to: "/contact", label: "Contact" },
];

Object.assign(window, {
  CATEGORIES, COURSES, OUTCOMES, CLIENTS, INSTRUCTORS, NAV,
});
